<a href="https://colab.research.google.com/github/Anushkaghei/Machine-Learning/blob/main/face_recognition_techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Comparing accuracies provided by different techniques such as SVM , PCA and CNN for face recognition based on applications of linear algebra.

SVM


In [ ]:
# Import necessary libraries
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris


# # Step 1: Data Collection
# # Load your dataset of labeled facial images and corresponding labels
# # X is the feature matrix, y is the label vector
# X, y = load_data()

# # Step 2: Feature Extraction
# # Extract relevant features from the facial images
# X_features = extract_features(X)

# # Step 3: Feature Representation
# # Represent the features in a suitable format
# # For example, flatten the feature matrix into a vector
# X_flat = X_features.reshape(X_features.shape[0], -1)

iris = load_iris()
X = iris.data[:, :2]  # we only take the first two features.
y = iris.target

# Step 4: Model Training
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the SVM classifier
svm = SVC(kernel='linear', C=1.0)

# Train the SVM classifier
svm.fit(X_train, y_train)

# Step 5: Model Evaluation
# Predict labels for the test set
y_pred = svm.predict(X_test)

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)


Accuracy: 0.9


PCA

In [ ]:
# Import necessary libraries
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

# Load the Olivetti Faces dataset
iris = load_iris()
X = iris.data[:, :2]  # we only take the first two features.
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# Step 1: Feature Extraction
# Perform Principal Component Analysis (PCA) for dimensionality reduction
n_components = 2  # Number of principal components to keep
pca = PCA(n_components=n_components, whiten=True, random_state=1)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

# Step 2: Model Training
# Initialize the SVM classifier
svm = SVC(kernel='linear', C=1.0)

# Train the SVM classifier
svm.fit(X_train_pca, y_train)

# Step 3: Model Evaluation
# Predict labels for the test set
y_pred = svm.predict(X_test_pca)

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)


Accuracy: 0.8


CNN

In [ ]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])

x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
#print(y)

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=10)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]
Neural Network Model Summary: 
Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 fc1 (Dense)                 (None, 10)                50        
                                                                 
 fc2 (Dense)                 (None, 10)                110       
                                                                 
 output (Dense)              (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/10


/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


24/24 - 1s - loss: 1.1728 - accuracy: 0.3250 - 649ms/epoch - 27ms/step
Epoch 2/10
24/24 - 0s - loss: 0.9865 - accuracy: 0.3500 - 50ms/epoch - 2ms/step
Epoch 3/10
24/24 - 0s - loss: 0.9136 - accuracy: 0.3667 - 49ms/epoch - 2ms/step
Epoch 4/10
24/24 - 0s - loss: 0.8498 - accuracy: 0.3333 - 51ms/epoch - 2ms/step
Epoch 5/10
24/24 - 0s - loss: 0.7980 - accuracy: 0.5750 - 59ms/epoch - 2ms/step
Epoch 6/10
24/24 - 0s - loss: 0.7590 - accuracy: 0.6833 - 57ms/epoch - 2ms/step
Epoch 7/10
24/24 - 0s - loss: 0.7125 - accuracy: 0.7083 - 59ms/epoch - 2ms/step
Epoch 8/10
24/24 - 0s - loss: 0.6719 - accuracy: 0.7500 - 56ms/epoch - 2ms/step
Epoch 9/10
24/24 - 0s - loss: 0.6305 - accuracy: 0.7250 - 59ms/epoch - 2ms/step
Epoch 10/10
24/24 - 0s - loss: 0.5857 - accuracy: 0.7833 - 61ms/epoch - 3ms/step
1/1 [==============================] - 0s 205ms/step - loss: 0.5840 - accuracy: 0.7000
Final test set loss: 0.583998
Final test set accuracy: 0.700000
